# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - fincastly

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    yarn
    yarn add -D jest-standard-reporter
    yarn jest --reporters="jest-standard-reporter"
  displayName: 'test'

- script: |
    npm install
    npm run build
    cp ./package.json $(Build.ArtifactStagingDirectory)/package.json
    cp ./lib $(Build.ArtifactStagingDirectory)/lib -r
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
